### ISSUE TITLE
Is jekyll-paginate required, not optional?

### ISSUE THREAD

**Issue by joelpurra** [field-theory/jekyll-category-pages#1]
Tried to install and use `jekyll-category-pages` without pagination.

Here's (part of) the error message.

> /home/git/.gem/ruby/2.3.0/gems/jekyll-category-pages-1.0.0/lib/jekyll/category_pages.rb:38:in `generate': uninitialized constant Jekyll::CategoryPages::Pagination::Paginate (NameError)

Is the dependency `jekyll-paginate` actually required?

Didn't want to use pagination (initially), but couldn't get it to work until I added `jekyll-paginate` to my `Gemfile`. Apart from that, leaving pagination otherwise unconfigured has worked so far and category pages seem to be generated properly.

**Comment by field-theory** [comment]
Yes, although the documentation says that this plugin is only needed if you actually use pagination, there is still an implicit dependency that I didn't notice. The tests run with and without pagination, but the plugin is always installed when they are running.

I'll see if I can remove this dependency when it is not required.

**Comment by field-theory** [comment]
I figured that changing the requirement (i.e., checking if `jekyll-paginate` is installed and using a different code-path if it is not) is neither stable nor worthwhile. So, I have updated the documentation instead and made `jekyll-paginate` a required dependency.
