### ISSUE TITLE
Categories with certain character combinations not working.

### ISSUE THREAD

**Issue by dust-io** [field-theory/jekyll-category-pages#10]
Hi @field-theory — I'm not sure if this is a bug or how it's built, but if you have a category such as: 'Books & Publications' the url after slugify is: 'books-publications' but the folder generated in the `_site` is 'Books%20&%20Publication' — not sure if this is a quick fix, it'd be great to have this work.

**Comment by field-theory** [comment]
That looks like a bug to me ... I can write a test case and then we find the origin of the inconsistency.

**Comment by field-theory** [comment]
I have been able to reproduce this issue. It occurs whenever you use special HTML entities (like `&` or `<`) in categories and is not bug in the plugin, but in Jekyll.

Jekyll does not properly escape collection names when constructing the path of a page. While the categories plugin handles the category names properly, the URLs of the pages and posts with categories contain the raw characters which is invalid if they contain certain entities in a variety of situations (e.g., any `feed.xml` Jekyll generates is invalid).

I am not sure if there is anything I can do to fix this. The workaround is to not use collections in paths at all (which is probably the best solution, anyways). So add something like:
```
permalink: /:year/:month/:day/:title:output_ext
```
to your `_config.yml`.

**Comment by field-theory** [comment]
I have added this issue and the workaround to the documentation.
