### ISSUE TITLE
Not working On Github?

### ISSUE THREAD

**Issue by danielricecodes** [field-theory/jekyll-category-pages#11]
Hello!  I am having issues getting Category Index pages to appear on my production site (Github Pages).  Everything works great locally (e.g. `JEKYLL_ENV=development`); however, the category index pages that are generated locally appear to be missing on production.  Any one else had this problem?  I'm not sure where to start since Github builds the site automatically on their own and I can't tell if there are any errors or not.  

Localhost is fine:

<img width="1289" alt="Business" src="https://user-images.githubusercontent.com/169038/76984969-ebd42500-6915-11ea-9a8c-d23db87d7533.png">

Production is missing:

<img width="1044" alt="Page_not_found_·_GitHub_Pages" src="https://user-images.githubusercontent.com/169038/76991242-a0267900-691f-11ea-92d8-eb5b9fe7bf34.png">

Thanks in advance!

**Comment by field-theory** [comment]
This is actually a bug (sorry, a "feature") of GitHub Pages. The documentation on https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll says:

> GitHub Pages cannot build sites using unsupported plugins. If you want to use unsupported plugins, generate your site locally and then push your site's static files to GitHub.

The list of supported plugins is [here](https://pages.github.com/versions/) and does not contain the category pages plugin.

Thus, the workaround is to generate the site locally and then upload the resulting static files to GitHub.

**Comment by danielricecodes** [comment]
Ouch, thats super lame and really buried in the documentation.  Thanks for sharing!

**Comment by danielricecodes** [comment]
Ok - I got my site working.  It's not super obvious how to do this, but I had to create a NEW repository, push the contents of `_site` to it, and add `.nojekyll` to the root directory.  Frustrating just to get "non-sanctioned" plugins to work 👎

**Comment by field-theory** [comment]
Sorry about that ... but thanks for sharing the solution!
