### ISSUE TITLE
Is there a way this can be used for tags as well?

### ISSUE THREAD

**Issue by tamouse** [field-theory/jekyll-category-pages#2]
I'm using both categories and tags in my posts. I'm wondering if there is a way to use this to generate tag index pages as well?

**Comment by field-theory** [comment]
No, unfortunately this plugin is only aware of categories and not of tags. For tags you need a different plugin.

**Comment by tamouse** [comment]
I forked it and made one: https://github.com/tamouse/jekyll-tag-pages
