### ISSUE TITLE
Upgrading to jekyll-paginate-v2

### ISSUE THREAD

**Issue by rishabh** [field-theory/jekyll-category-pages#3]
Hi,

First of all, thank you for the plugin!

I was wondering if you were planning on upgrading from the old jekyll-paginate plugin to jekyll-paginate-v2?

Thanks!

**Comment by field-theory** [comment]
As far as I know the jekyll-paginate gem was the default in Jekyll v2 and is still the [recommended install on Jekyll v3](https://jekyllrb.com/docs/pagination/). On the other hand, the new [jekyll-paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md) claims to also feature category and tag pages. These may also contain spaces and special characters.

I haven't tried it so I do not know how good these are actually working. But I wonder: if you are willing to use jekyll-paginate-2 anyways, what are you missing from jekyll-paginate-2 that jekyll-category-pages offers?

**Comment by rishabh** [comment]
You're right, my apologies!

jekyll-paginate-2 seems to generate the as well category pages (with a bit of additional work).
