### ISSUE TITLE
Hide category pages in standard menu?

### ISSUE THREAD

**Issue by futur22de** [field-theory/jekyll-category-pages#6]
Hello,

your plugin is nice. But I have about more than 100 categories. I don't want them so show in the standard menu. Could you implement a simple parameter or if statement to hide the categories in the main menu? I show the categories in the sidebar.

Thanks.

**Comment by field-theory** [comment]
Hi, I don't quite understand what you mean by "main menu" and by "sidebar". Does your question refer to a specific design or to the category pages plugin?
